### ISSUE TITLE
Teaching Meetup on 11 Sept, 2016 (Sunday)

### ISSUE THREAD

**Issue by nishant-tomer** [fcc-hyd/meetups#12]
Two topics people already want - 
1. concept of `this` and `call`, `apply` and `bind` etc. ~ rahul
2. what is the structure of a web app and how it differs from other forms of softwares and how to setup a backend for a web app. ~ Pavan Boro and friends

One idea i want to do is to show this video - [Must Know for a Web Dev](https://www.youtube.com/watch?annotation_id=annotation_1494970401&feature=iv&index=6&list=PLoYCgNOIyGAB0_YBfdNP5oqAD98HtAQqL&src_vid=zXqs6X0lzKI&v=pB0WvcxTbCA)

The idea is to play and stop at places and explain if people want otherwise take questions in the end and explain more. 

This video is i think super helpful in the sense that while doing curriculum one feels like curriculum is not teaching them tools which are used commonly and one feels a disconnect. 

I just want to explain what is the purpose of each category of tools and why they are not needed when one is just starting out and how will they be able to learn them if they ever need to.

what do you guys think?

**Comment by vramana** [comment]
* We can explain those particular things but what will be the overall theme of the meetup? If you want to teach entire JavaScript, that's also fine with me. I want to see what new things you want to bring to the teaching meetups.

* What do you explain as the structure of web-app? To me it's as simple as `styles` and `scripts` folders for most small to medium level projects. Please elabore. 

*  What softwares do you want to compare against? Which backend do you want to showcase? MEAN stack?  

* At SLN Terminus, you already explained the aims of the cirriculum. Repeating it again this quickly kind of feels boring. We can do it after a few weeks. 
  
  A related question is How often should we do this? I think once a month is fine.

**Comment by duttakapil** [comment]
- I've provided Rahul with [this article on apply, call and bind](javascriptissexy.com/javascript-apply-call-and-bind-methods-are-essential-for-javascript-professionals/). I think that should be enough. 
- This doesn't need to be taught separately. If and when we build our own community projects with more complicity, it will indirectly teach the participating members the standard structure for web apps. 
- This video is old now (2015). Here is the [2016/2017 MUST-KNOW WEB DEVELOPMENT TECH](https://www.youtube.com/watch?v=sBzRwzY7G-k) they released recently. 

I like the idea of the video, but I don't think we should just be showing them and then explaining. We can directly use the [MindMap he uses](https://coggle.it/diagram/Vz9LvW8byvN0I38x) and talk about each of those things. We can later share the video as well. 

If we do that, we can call the meetup "State of Web Development in 2016" or something, which might provide some marketing value. 

We'll have the real time discussion on this when we meet on 3rd September.

**Comment by vramana** [comment]
I want @nishant-tomer to take lead of this teaching meetup. If you want to do a "State of Web Dev 2016" meetup then we can do it after this one.  

@nishant-tomer First pick a theme that you are comfortable with. I will try to think up some themes. You can tell if you are comfortable.

**Comment by duttakapil** [comment]
@vramana we decided today to go with the mind map. @nishant-tomer and Chuck will be taking the lead and we're thinking of calling it "Everything you need to know about Web Development - 2016"  
I'm going to create the event page tomorrow. 
Any thoughts or concerns?
