### ISSUE TITLE
Plan for 4 meetups after Sep 11 

### ISSUE THREAD

**Issue by vramana** [fcc-hyd/meetups#13]
## 25 Sep (Sun)

**Format**: Live Coding Meetup
**Venue**: ThoughtWorks Hyderabad

## 1 Oct (Sat) 

**Format**: Practice Meetup
**Venue**: Colaborate

## 9 Oct (Sun) 

**Format**: Teaching Meetup
**Venue**: Progress Software

cc @fcc-hyd/organisers

**Comment by duttakapil** [comment]
I suggest to switch 1st Oct and 9th Oct. Every meetup should have at least two weekends of gap before they repeat. So 1st Oct - Teaching meetup and 9th Oct - Practice meetup

**Comment by vramana** [comment]
I want to think we can teach how to host static html pages on github.  But that wil not take 3 hours. It will take 30-45 mins at max. Probably we can do it part of Practice meetup. What do you guys think?

**Comment by duttakapil** [comment]
We can do another Intro to Git and GitHub meetup, and include this in that @vramana @nishant-tomer

**Comment by vramana** [comment]
Like last time we can't use c9. How do you plan to do it? 

BTW I created a org team @fcc-hyd/organisers which will ping all of us at once. You don't need to reping again unless you are replying to a specific person.

**Comment by duttakapil** [comment]
We can do it locally? We went with C9 last time only because we wouldn't have to deal with settings things up for each member. But now we can ask them to try setting things up before hand, and if they fail, we can help them out before starting the meetup.

**Comment by vramana** [comment]
What will we use Github for Windows ? Git command line? Most people will have windows so we have to keep that in mind.

**Comment by duttakapil** [comment]
Git Bash, ya. It comes with GitHub GUI for Windiws

**Comment by vramana** [comment]
I am afraid that we will run into it's dark corners without explicit practice before hand.
