### ISSUE TITLE
My Plan For The Future (Long Post)

### ISSUE THREAD

**Issue by duttakapil** [fcc-hyd/Meetups#5]
As promised, here is my detailed post on what I've been thinking : 

# Current State
We have conducted two meetups till now, both at Collab House. The agenda for the first meetup was to introduce yourself and pair program, for which around 18 people turned up. The agenda for the second meetup was to pair program and show our personal projects (WikiWars), for which some 12 people turned up (including the mentors). In that time, our WhatsApp and Discord room's have grown to 30+ members. We've conducted both the meetups at a very short notice i.e. booked the spot and planned it out just 3 or 4 days prior. This works well for individual meetups, but if we aim to really build a strong local developer community overtime, we'll need to plan much ahead with a crystal clear clarity of what we're trying to achieve. 

To me personally, the second meetup was a disappointment. There was far less participation, and things just didn't go as planned. @vramana couldn't do his 10-15 talk that he had planned, and I couldn't show my WikiWars projects. And even Collab seemed very occupied due to their anniversary party that evening. All this could have been avoided with much better planning. Our planning right now is weekly based. We start thinking about the next meetup only when we're done with the previous one. This leaves us with no overall direction or path. We can't keep doing just pair programming or decide to randomly teach some tool like Git or Angular. 

# The Problem 

One of the major problems that I've noticed, based on our previous two meetups, is the member attendance/participation. We can't form a cohesive local community if we don't have a consistent presence of the same people at least for a certain period of time. The other big issue is attendance of absolute beginners (to FreeCodeCamp or JavaScript) at a regular meetup. We are not able to pay enough attention to them and they disturb the bond we're trying to create in the community. 

But the biggest problem we face is that we do not have a structure. We are not organizing our meetups is any particular order or flow. 

# The Solution

The obvious solution is **we need a flow**. We need to create a structure and follow it strictly. Only then can we predict our growth as a community. 

### My Idea 
We'll organize our meetups with a monthly plan. There will be four official meetups :

1. Beginner : This will be in the first week of the month. In this meetup, we'll introduce the attendees to FreeCodeCamp, talk about Web Development, introduce them to the basics of HTML and CSS and the fundamentals of JavaScript. We can do this by following the FCC Curriculum or use external resources. We'll announce this meetup publicly, creating a Facebook and Meetup.com event page and mostly hold it at Purple Talk*, because of its spacious environment. 

2. Intermediate : This will be held on the 2nd weekend of the month. In this meetup, we'll teach Object Oriented JavaScript to the campers. This will be a closed meetup, so only the WhatsApp and Discord group members will know about it. We can make the campers do at least two Object Oriented Js challenges from the curriculum. We'll hold this meetup at Fission Labs/Collab House*, expecting some new comes from first week to drop off. 

3. Advance : This one will be held on the 3rd weekend of the month. In this meetup, we'll teach Functional Programming with Js to the campers. Just like the last one, we'll announce this only in the group. We want to block all channels by which absolute beginners might find out about this meetup. We can hold this one at Collab House/Fission Labs*. 

4. Bonus (for lack of a better word) : This one will be held on the fourth weekend of the month. In this meetup, we'll introduce the campers to additional tools like Git/GitHub and even give a basic description of Frameworks/Libraries like Angular/React, intro to Node Js, understanding the CLI etc. We can hold this one at Whiteboard Cafe/The Valley*.

For this to really work, we'll need to do a few things. We'll have to create three private Discord rooms for the last three official meetups. So that, when a camper attends one, we can manually add them to the room. For example, after the _beginner_ meetup, if a camper attends the _Intermediate_ meetup, we'll add them to the room _Intermediate_ where they can talk to other campers at the same level as them and also discuss about the next meetup. 

We'll also have to make it very clear that we expect all campers to make their own progress in between the meetups. For example, after the _Intermediate_ meetup, we'll provide the attendees with some additional resources and ask them to work on some more challenges till the next meetup. Then when we meet again for the _Advance_ meetup in the 3rd week, the campers can ask us doubts they have collected over the week. And of course, we'll encourage them to approach us virtually as well.

Think of it like a pipeline. `You attend the meetup -> make progress on your own -> have some doubts -> get them cleared virtually or in the next meetup -> learn new concepts -> get added to a new room -> find out about next meetup -> repeat` 

And this goes on for one month. 

## Digging Deeper and Pair Programming
But this is obviously not going to be enough. We'll also need specific meetups to dig deeper into some concepts, specially the ones introduced in the last meetup of the month. We will still do that, but in a different way. We'll create more private Discord rooms for each main tool, like Git, Node js, Angular, React etc (let's call them themed rooms) and only add people who have attended all the four official meetups. In these rooms, we'll talk about the tool/subject in question and help out campers who are learning/exploring them on their own.  Then we'll leave them on their own. From here on, the campers in each themed room can start organizing their own independent meetups, unrelated to the official four meetups we'll be doing. In these independent meetups, the campers can pair program to build something using the tool they are learning or one of us can organize a "Digging Deeper [into tool]" specifically for that room. So for example, if we have a React room, @vramana can hold a "Digging Deeper into React" meetup unrelated to our four official meetups. It is not mandatory for me or @alayek to attend this meetup. And if Ramana is busy, the React room members can organize a Pair Programming meetup on their own. Does this make sense?

These meetups can take place at the 91SpringBoard/Whiteboard Cafe Cafeteria/any coffee shop/lounge. They can take place on the weekdays or the weekends and they'll be organized by the members of the themed room. No one else outside these rooms will/should find out about these meetups. 

## Beyond Meetups 

All that sounds great. But it is again not enough to truly build a strong local community. As we spoke in the first meetup, we'll need to have active virtual conversation on a daily bases. I'm not expecting our members to be online all the time or want to push them to have more virtual conversation. But I believe that many, if not most, of our member do want to talk more but are shy or cannot find a topic to talk about. I've also noticed that we mentors converse with the members only when one of them posts a question/code for review or help. This dims down our conversations as a group, because we're all waiting or expecting someone else to start a conversation. It's basic human nature. What we can do here is take the pressure off of their shoulders. What i'm suggesting is, we the mentors should come up with more topics to talk about in the group. It can be as simple as sharing some tutorial link or the top post from HackerNews on that day. But we have to be the ones to get he ball rolling. Only then will we start having more active conversation virtually and make the members feel more comfortable. 

## More Mentors

If we're going to make this happen, we need more mentors. One thing we could do is, ask people who have attended all the four official meets and are comfortable with one or two advanced tools, to help us out with the beginners. That way, even when we three are busy or tired, the meetups can keep going. 

...

\* These locations are not compulsory for the specific meetup. I just think if we have them all planned from the start of the month and confirm them, it would be great. We can change the locations for each official meetup as we like.

I think that is it. So what do you guys think? Criticism/Suggestions/Opinion? 

P.S. I just found out that you cannot exactly create private rooms in Discord. But you can create new roles and assign them to members, then create rooms specifically for those roles. We should still be able to work this out, I think. 

@vramana @alayek

**Comment by alayek** [comment]
I think having to publicize only one meeting a month, gives us enough scope to prepare well ahead of time. 

Once you are in the meet, the interest would grow organically - we won't have to publicize for closed meets. Except within group members.

----

Great! I like this. We would get steady influx of people from all kinds of backgrounds. But I hope we are prepared enough to be able to speak in front of a diverse audience.

**Comment by vramana** [comment]
Beyond Meetups is the only section I liked. The rest seems to complicates things. I can't handle complexity.  My involvement with FCC is just an attempt to find a platform for me to teach. One of my other goals is to build a community. If this is complexity is what people believe is necessary to make to strong community. I am not interested in taking part in this complexity. May be I don't understand a thing about growing communities. May be this is all essential complexity involved in making a strong community. I am really sad and frustrated with all this complexity.

So, Do I have better alternatives? Nope. Not any at the moment. I am just super sad looking at all this.

**Comment by duttakapil** [comment]
@alayek thanks for your response. We indeed need more practice in public speaking and teaching on a large scale to a diverse audience. We'll hopefully learn as we go forward. 

@vramana relax. Take a deep breath. You don't have to stress over this. That was the point of my post, to make it simpler for us to organize these meetups, so we don't have to stress over every single one individually. 

> My involvement with FCC is just an attempt to find a platform for me to teach. One of my other goals is to build a community.

No one is taking that away from you. You're still building a community where you teach and help people out. 

The reason why all this seems complicated to you is because it's a whole essay of new thoughts you're suddenly expected to understand and follow. I suggest you give more thought to this, take your time. Trust me, this will make everything simpler. 

Let's me help you out here. You saw the empty drive folder I created right? Now image four folders inside it, one for each official meetup. Each of these four folders will contain all the material that we require for these meetups. The presentation, resource document, spreadsheet with all the attending participants etc. That is all we need. We just take these materials and teach the members using them and repeat the process every month. No more planning required for each meetup. And after enough time passes, other experienced members can replace us and mentor the beginners. 

We only have to put effort in the "Digging Deeper" meetups, where you'll have all the freedom to teach the subject as you like without the interference of other mentors. And with the pair programming meetups, we don't even have to think about them. We'll give the campers the freedom to organize them as they wish i.e once they've attended all the meetups. This takes the pressure off our shoulders and makes things much simpler. Once we get into the flow, you'll see how much easier it will become to organize our meetups, while also growing our community at a study pace. 

## Let's look at next month as an example 

### New Roles : 
There will be four new roles on Discord : Beginner, Intermediate, Advance, Master. 

### Chat rooms : 
Official Rooms : [ Beginner, Intermediate, Advance ], 
Themed Rooms : [ Git/GitHub, Angular Js, Node Js, React Js, Databases, D3 Js, etc ]

### Schedule 
- 9th July : Beginner Meetup at Purple Talk for new comers. Introductions -> show FCC Curriculum -> Teach HTML/CSS, Js fundamentals.
- 10th - 15th July : Beginner role awarded. Practice of topics from last meetup.
- 16th July : Intermediate Meetup at Collab House. Clear doubts/Live Discussion/Teach OOJs.
- 17th - 22nd July : Intermediate role awarded. Practice of topics from last meetup.
- 23rd July : Advance Meetup at Fission Labs. Clear doubts/Live Discussion/Teach Functional Programming in Js.
- 24th - 29th July : Advance role awarded. Practice of topics from last meetup. 
- 30th July : Master Meetup at Whiteboard Cafe. Clear doubts/Introduce to Git/Angular/React/Node Js etc. 
- Master role awarded and automatically added to all themed rooms.
- Digging Deeper meetups organized on any date by any mentor. 
- Pair Programming meetups organized on any date by the master members at any place.

Now this might all still seem very complicated. But that is because I'm condensing the plan for an entire month into few lines of text. And notice how the underlying structure for each meetup is just a copy of the previous one. 

And that is it. You'll still be doing what you want to do, but with a better overall plan. I hope I could explain my perspective well enough. I just want you to see how many problems such a structure can solve/avoid. Hopefully this helped, instead of making it seem even more complicated.

**Comment by vramana** [comment]
> The reason why all this seems complicated to you is because it's a whole essay of new thoughts you're suddenly expected to understand and follow. I suggest you give more thought to this, take your time. Trust me, this will make everything simpler.

You don't understand why I am upset. It is the structure that upsets me. Whenever I mentioned complexity, I am looking at the very structure you are proposing. 

> Now this might all still seem very complicated. But that is because I'm condensing the plan for an entire month into few lines of text.

I am not upset because I am unable to read a few lines in english. I am upset because you are trying to fit a programmer's learning journey into a month and convince them that somehow they have reached an advanced level.

I have purposefully left out all my opinions about why these things feel wrong, misguided and complicated to me. Instead of trying to ask why I may have felt that way, you must really have thought this guy lacks reading comprehension so let me help me him understand things. Is that how it is? :joy:

At best, I am an intermediate programmer. I only aware of a few language primitives and ideas. Probably I have a lot of holes in my basics too. As you know from the other day, I don't even know `for-in` works. :disappointed: I don't even understand how to use these language primitives. So, I really don't belong in those Advanced or Master roles.

I have said this on Monday too. I am not doing any React specific stuff under FCC Hyd at least in the forseeable future. If others are interested in doing so, please go ahead.

> Teach OOJs.

:joy::joy::joy::joy::joy::joy: 
:+1:  ** 1000

Teach OOJs whatever it is. (Oh I understood OOJs stands for Object Oriented JavaScript otherwise I will get `Reading Comprehension` remark).

**Comment by duttakapil** [comment]
> #  :tired_face:  FACEPALM :tired_face:

Okay. Let's break this down. 

> The rest seems to **complicates** things. I can't handle **complexity**... If this is **complexity** is what people believe is necessary to make to strong community. I am not interested in taking part in this **complexity**. May be I don't understand a thing about growing communities. May be this is all essential **complexity** involved in making a strong community. I am really sad and frustrated with all this **complexity**.

Can you point out to me where in your six mentions of complexity you indicated that you understood the underlying structure, but did not _like_ it?

> I am upset because you are trying to fit a programmer's learning journey into a month and convince them that somehow they have reached an advanced level.

### NO! No. no no no no no no. No.

That is NOT what I'm trying to do. Gosh, why is this so hard? 
I do not want to waste more time explaining this. Let's just change the names for your sake. 

# Revamped look at next month

### New Roles :
There will be four new roles on Discord : Level 1, Level 2, Level 3, Level 4.

### Chat rooms :
Official Rooms : [ Stage 1, Stage 2, Stage 3 ], 
Themed Rooms : [ Git/GitHub, Angular Js, Node Js, React Js, Databases, D3 Js, etc ]

### Schedule :
- 9th July : Level 1 Meetup at Purple Talk for new comers (Public Event). Introductions -> show FCC Curriculum -> Teach HTML/CSS, Js fundamentals.
- 10th - 15th July : Level 1 role awarded and automatically added to Stage 1 room. Practice of topics from last meetup.
- 16th July : Level 2 Meetup at Collab House (Private Event). Clear doubts/Live Discussion/Teach OOJs.
- 17th - 22nd July : Level 2 role awarded  and automatically added to Stage 2 room. Practice of topics from last meetup.
- 23rd July : Level 3 Meetup at Fission Labs (Private Event). Clear doubts/Live Discussion/Teach Functional Programming in Js.
- 24th - 29th July : Level 3 role awarded  and automatically added to Stage 3 room. Practice of topics from last meetup.
- 30th July : Level 4 Meetup at Whiteboard Cafe (Private Event). Clear doubts/Introduce to Git/Angular/React/Node Js etc.
- Level 4 role awarded and automatically added to all themed rooms.
- Digging Deeper meetups organized on any date by any mentor.
- Pair Programming meetups organized on any date by the master members at any place.

Does this help?!

> I have purposefully left out all my opinions about why these things feel wrong, misguided and complicated to me. Instead of trying to ask why I may have felt that way, you must really have thought this guy lacks reading comprehension so let me help me him understand things. Is that how it is? :joy:

Why? Just why? Why in the name of JavaScript would you do that? Why would you keep your thoughts/opinions to yourself, when you're specifically asked to put them forward? If you would have made your concerns/issues clear yesterday, I would have addressed them and we would have moved on. But now here we are stuck in this loop again.

Why are you stuck with the "reading comprehension" comment? You've mentioned it twice in your comment and at least six times since I said it days ago. If you really took that to heart then I apologize. Now can you get over it so that we can have some productive discussion? 

> At best, I am an intermediate programmer. I only aware of a few language primitives and ideas. Probably I have a lot of holes in my basics too. As you know from the other day, I don't even know for-in works. :disappointed: I don't even understand how to use these language primitives. So, I really don't belong in those Advanced or Master roles.

Hope the revamped names help you out here. If you're not comfortable with teaching JavaScript Objects for the Level 2 meetup, then that's fine. We can figure things out. 

> I have said this on Monday too. I am not doing any React specific stuff under FCC Hyd at least in the forseeable future. If others are interested in doing so, please go ahead.

That is fine. I just used it as an example to explain my thoughts. Doesn't mean you'll have to teach React. 

>  Teach OOJs.
   :joy::joy::joy::joy::joy::joy: 
   :+1: ** 1000
   Teach OOJs whatever it is. (Oh I understood OOJs stands for Object Oriented JavaScript   
   otherwise I will get Reading Comprehension remark).

I don't know what to say to this. Is this a joke to you? Are you suggesting OOJs is not a real thing? If yes, then I suggest you go through these links : 
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Introduction_to_Object-Oriented_JavaScript
- http://eloquentjavascript.net/06_object.html
- http://javascriptissexy.com/oop-in-javascript-what-you-need-to-know/
- https://www.udacity.com/course/object-oriented-javascript--ud015

I also suggest that you go to the FreeCodeCamp website and see if there is any symmetry between the structure I penned above and the FCC curriculum.

Also, since you do not like this structure, can you please provide your own alternative that resolves all the problems that we face? It needs to provide a periodic plan that repeats every few weeks so that all the members can attend our meetups without feeling missed out. It needs to provide a order and maintain a consistent influx of new members and attendance of current members. It needs to figure out how we can teach HTML/CSS to absolute beginners and Node Js to more advanced members who are all part of the same group, all at the same time. And finally, help us grow as a community. 

One last thing, what happens in each official meetup doesn't necessarily have to be how I described it. If we can all agree on the underlying structure of _how_ we'll organize these meetups, we can discuss on _what_ we'll teach in each individual one. 

@vramana @alayek

**Comment by rhhhhl** [comment]
Hi guys, kind of stumbled into your conversation here .... i really like your enthusiasm to teach and form a strong community. Some free advice, you are doing great.
1. @vramana take 30 mins in a meetup focus on react(since you are known for it) and assign to your links(material) and show the members what they can achieve and how to get a job in reactjs. In the second meetup discuss the members who are into react, their problems, going the materials and so forth. And you don't have to teach the complete course, we are in need to get jobs, so show us the end target where we can reach by learning these tools, you will be amazed for the next meetup how people get transformed. :)
2. @duttakapil keep up your organizing skills ! make a meetup into 2-3 diff topics on 1.**tools**(git, angular, and discuss new tools travis, ruby, etc,.), 2.**ways to learn**(videos, materials, books etc.,.) 3.**reaching out for help**(forum, chat etc.,.). Newbies, intermediate and pros if they cant attend their specific meetups. so respond to everyone :+1: (i am in a confusion, whether i am a beginner or intermediate programmer, like my kind of people).
3. @alayek you were a great resource and you are a go to guy for any problem, if you can jump between the 2-3 sessions simultaneously happening in a meetup and help of the instructors and members that would be great :+1: 
P.S. I  struggled to learn code since few years, found great tools and tutorials, but can't finish and practice them, really felt great teaming up with fcc-hyd :100:

**Comment by duttakapil** [comment]
@rhhhhl thanks for your input. We'll consider your suggestions and see what we can do. :smiley:
