### ISSUE TITLE
Ideas for Live Coding Meetup

### ISSUE THREAD

**Issue by duttakapil** [fcc-hyd/meetups#8]
In this issue, we'll ideate and discuss the ideas for the next few live coding meetups. 

The challenge is to finalize on projects that are neither too basic nor too complicated. It should be exciting enough to peak the members interest and realistic enough to build a working model under ~3 hours.

I couldn't come up with much. But thought having a place to just throw around ideas and discuss would be better. 

Few ideas off the top of my head that we could consider :
- Basic web version of some arcade video game (pong, tetris etc) 
- Basic chat application
- Basic chrome extensions 
- Our own website

Now I'm not claiming I know how to build any of that. And it's not necessary that we should pick one of these for our upcoming live coding meetup (27th Aug). These are just things we could consider. We could execute them much later, when we are more confident. Right now, the motive is to just throw around some ideas and discuss. 

So, what do you think about these suggestions and do you have any ideas you'll like to suggest?

**Comment by khaledMohammed000** [comment]
#Basic Chrome extension
>Adding to that if we can make a extension something like this : https://chrome.google.com/webstore/detail/android-sdk-search/hgcbffeicehlpmgmnhnkjbjoldkfhoin?hl=en

Idea is we will make something same for Stackoverflow , **I use the above extension , its so damn useful**
or we could search Mozilla developer network

**Reason :** 
>I am directly searching the website without going to it and also with out having to type crazy long keywords in search

> Downside : this would be really specific to just one website as seen in the above extension by roman nurik

**Comment by duttakapil** [comment]
I love your idea to create an extension that provides a special keyword you can type in the omnibox that let's you search MDN. I use [this Chrome Extinction](https://chrome.google.com/webstore/detail/bookmark-search/hhmokalkpaiacdofbcddkogifepbaijk) to search my bookmarks easily, which is great. 
We should definitely consider this as a live coding project.

**Comment by vramana** [comment]
Please visit https://devdocs.io

**Comment by vramana** [comment]
@Khaled I don't think you have written a lot of code. Even some of @duttakapil suggestions are pretty hard. There are just not possible to do in 3 hour span. We may not even complete 10% of the project if we go total blind. 

Even after working a lot in JS. I don't feel confident enough to say that I can do these in 3 hours. I am suprised at the level of optimism you guys have.

**Comment by duttakapil** [comment]
@vramana the goal of this format is not to finish the project but to expose the audience to the actual development process. Essentially, we're trying to answer these questions : 
- How do people build something from the scratch? 
- What do they do when they get stuck? 
- What is their thought process? 

We're trying to show the human side of building something. 

Also, the point of this issue is to be a dumping ground for possible ideas for a live coding meetup. As I mention in the post..
>The challenge is to finalize on projects that are neither too basic nor too complicated. It should be exciting enough to peak the members interest and realistic enough to build a working model under ~3 hours.

We'll finalize on ideas that seem more realistic. But right now we need a list of ideas to consider first.

**Comment by vramana** [comment]
Hmmm.  It's like we are asking them to come for a full meal and they may have to leave right after starters. We have to atleast serve them the main course. 

Building games in front of crowd with time limit is pretty hard. You may end up thinking a lot about about how to encapsulate the game physics into logic and not write the logic at all. And the logic may be extremely twisted. The whole process may take a few days or a week. It just don't feel it's right to show 3 hours of it. Youtube VODs are better suited to watch live coding. They give the complete experience. I am only talking about games.

We getting struck till some point is okay. Beyond that people will lose interest. I want to avoid that. I want to tackle things that are in our scope very much but we have never done them.

I have an idea. Let's build Github's Header that matches it pixel to pixel. How does that sound?

**Comment by duttakapil** [comment]
@vramana seems too simple but I'm game. We need to experiment the idea with something.  What about the GitHub API project I mentioned in the Schedule trend? That's simple enough and doable in under 3 hours. 
@nishant-tomer what do you think?

**Comment by vramana** [comment]
OKay. Then let's build the profile sidebar. We have already discussed this idea in the past.

**Comment by duttakapil** [comment]
Another suggestion, as I mentioned in #10, is that we build our website from scratch in our live coding meetups. We can then ask the members to contribute thus making them familiar with open source. 
But let's go with the GitHub Sidebar Project for 27th August. 
We can start building our website in the next live coding meetup.
