### ISSUE TITLE
Planning for the Web Developer Meetup (casual hangout meetup)

### ISSUE THREAD

**Issue by duttakapil** [fcc-hyd/meetups#9]
In this issue, we'll plan out the causal hangout meetup we're doing on the 3rd of September. Right now, the plan is to just get people together and let them interact. If you'll like to include some activity or have some more ideas, please share them here. 

We also need to focus a bit on the marketing side, as this one is not just for our community but also those from outside who are interested/learning/professionals in web development. 

### Details : 
Title : Web Developer Meetup
Date : 3rd September, 2016 
Time : 3 pm to 6 pm
Location : 91SpringBoard

**Comment by Pradhant** [comment]
1. Let's check if people want to do that. There's a high chance people will not show up. 
2. Let's still have a plan for a casual meet up. We need to think about "Why do we need this"?
3. Can we handle more new people than what we have now? 

 I say let's pause this and work on other meet ups.

**Comment by vramana** [comment]
@Pradhant Probably you haven't been active in whatsapp group. We asked in the group already. Some people are interested. 

All the whatsapp group may not show up. But still some will do and we are doing it for them. To make people comfortable and engaged in this community.

**Comment by duttakapil** [comment]
@Pradhant 
1. As @vramana said, we've already asked and people are interested.
2. We need this because our members don't really know each other, and are not comfortable engaging in a group of 80+ people. We don't want to create a ghost town. 
3. We don't have to do anything, except add them to our WhatsApp/Discord. 

This meetup is confirmed. We just have to discuss ideas for activities that could be included and the promotion aspects. Any suggestions for that?

**Comment by Pradhant** [comment]
Kool, I agree. I was just looking out for you guys because it happned once and no one turned up.   
Here are my thoughts. I dont know how helpful these might be...
We can have existing team members or some season coders to show a site/case study and open up a discussion? You think that'll work?

**Comment by duttakapil** [comment]
@Pradhant this is a good suggestion. But this might take quite some time and will block people from having actual individual interactions. I'm thinking we can let them all just introduce themselves and if they want to showcase something (their project or whatever), we'll give them a couple of minutes to do that. We'll mention that in the event description. What do you guys think?

**Comment by Pradhant** [comment]
Right on. Kapil, the intro will happen anyway. We must add something after that and yes it will take time for people to speak up but we have to start somewhere. 
I would mention it in the description but very briefly and not as a compulsion because that might turn them off. 

Here's another way to do it. 
Let's sit in two, intro to each other and the same activity as above. They will only have 6 mins with each other 3 mins each. They will have to be quick and brief. In the end we do some activity that'll show us how much people know who they talked to and have some fun with it.
